### ISSUE TITLE
[BUG]关于vercel部署问题

### ISSUE THREAD

**Issue by jinghuashang** [imsyy/site-status#13]
Error: No Output Directory named "build" found after the Build completed. You can configure the Output Directory in your Project Settings.

Learn More: https://vercel.link/missing-public-directory

报错如上，根据报错提示是如下
[缺少公共目录](https://vercel.com/docs/errors/error-list#missing-public-directory)
如果输出目录缺失、为空或无效（例如，它不是目录），[则生成步骤](https://vercel.com/docs/deployments/configure-a-build)将导致错误。要解决此错误，您可以尝试以下步骤：

确保在项目设置中正确指定[了输出目录](https://vercel.com/docs/deployments/configure-a-build#output-directory)
如果输出目录正确，请检查构建命令（[文档](https://vercel.com/docs/deployments/configure-a-build#build-command)）或[根目录](https://vercel.com/docs/deployments/configure-a-build#root-directory))
尝试在本地运行 build 命令，并确保在指定的输出目录中正确生成文件

**Comment by imsyy** [comment]
输出目录设置为 `dist`
