### ISSUE TITLE
获取监控数据时出错

### ISSUE THREAD

**Issue by maodaisuki** [imsyy/site-status#14]
好像出bug了，UptimeRobot 网站控制台正常。同一 API KEY 在使用其他应用构建时也能正常加载站点状态。在自建站点和demo站点均显示调用超限或请求错误，请刷新后重试。

错误页面
![图片](https://github.com/imsyy/site-status/assets/133942310/ab0026f6-4962-43d9-972c-05fe6922d949)

控制台报错
![图片](https://github.com/imsyy/site-status/assets/133942310/c0b5d107-8928-400c-8334-82ee6ad9aad6)

**Comment by imsyy** [comment]
可以将全局 API 地址改为 `https://cors.status.org.cn/uptimerobot/v2/getMonitors`，或者自行搭建
我的可能会有问题

**Comment by maodaisuki** [comment]
好的，谢谢！
