### ISSUE TITLE
数据请求失败

### ISSUE THREAD

**Issue by zy111x** [imsyy/site-status#38]
![image](https://github.com/user-attachments/assets/1d0ecbd6-258f-4bd9-a9b4-1b6f7d3e2e8c)
作者的网站好像也是这样

**Comment by ZhenHuangLab** [comment]
我的网站也出现了这样的问题

**Comment by XingJi-love** [comment]
# 修改成官网API接口链接，从新部署一下就可以解决了

<img width="894" alt="站点检测问题解决" src="https://github.com/user-attachments/assets/690fba48-3aca-462a-9d32-a6b43b9991e7">

![屏幕截图 2024-10-14 133257](https://github.com/user-attachments/assets/fe141576-9990-4e11-b411-fd799a7b835e)

**Comment by XingJi-love** [comment]
> ![图像](https://private-user-images.githubusercontent.com/150530845/376047804-1d0ecbd6-258f-4bd9-a9b4-1b6f7d3e2e8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4ODU0MzgsIm5iZiI6MTcyODg4NTEzOCwicGF0aCI6Ii8xNTA1MzA4NDUvMzc2MDQ3ODA0LTFkMGVjYmQ2LTI1OGYtNGJkOS1hOWI0LTFiNmY3ZDNlMmU4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwNTUyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWE2ZGNjNDY4MDI1NGU2NDBjOWNlOTcyYjVmNWMzNWU2NTdlMjdiMzhiZDk0Y2VmOWQ1MjhmNzZmZjVlYTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DXAdrkR2YvOsSM1xwoUCpHf1DTfE7nRQ-UZFKHtnTeU) 作者的网站好像也是这样

# 修改成官网API接口链接，从新部署一下就可以解决了

<img width="894" alt="站点检测问题解决" src="https://github.com/user-attachments/assets/690fba48-3aca-462a-9d32-a6b43b9991e7">

![屏幕截图 2024-10-14 133257](https://github.com/user-attachments/assets/fe141576-9990-4e11-b411-fd799a7b835e)

**Comment by ZhenHuangLab** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/150530845/376047804-1d0ecbd6-258f-4bd9-a9b4-1b6f7d3e2e8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4ODU0MzgsIm5iZiI6MTcyODg4NTEzOCwicGF0aCI6Ii8xNTA1MzA4NDUvMzc2MDQ3ODA0LTFkMGVjYmQ2LTI1OGYtNGJkOS1hOWI0LTFiNmY3ZDNlMmU4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwNTUyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWE2ZGNjNDY4MDI1NGU2NDBjOWNlOTcyYjVmNWMzNWU2NTdlMjdiMzhiZDk0Y2VmOWQ1MjhmNzZmZjVlYTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DXAdrkR2YvOsSM1xwoUCpHf1DTfE7nRQ-UZFKHtnTeU) 作者的网站好像也是这样
> 
> # 修改成官网API接口链接，从新部署一下就可以解决了
> <img alt="站点检测问题解决" width="894" src="https://private-user-images.githubusercontent.com/177649500/376119475-690fba48-3aca-462a-9d32-a6b43b9991e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTY3OTMsIm5iZiI6MTcyODg5NjQ5MywicGF0aCI6Ii8xNzc2NDk1MDAvMzc2MTE5NDc1LTY5MGZiYTQ4LTNhY2EtNDYyYS05ZDMyLWE2YjQzYjk5OTFlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwOTAxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzBiNDQ3M2M5MWQ4M2IzNDhkZjlhMjdlZWVmYTJlZjBjYmI4NjM5YTMxMzRjZjUzZjU3ODExNWE4MjU0ZDkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ee2M_CQ3YqO8V2ASHDc_7BWawiLLse7sTvucfyxQjvw">
> ![屏幕截图 2024-10-14 133257](https://private-user-images.githubusercontent.com/177649500/376119541-fe141576-9990-4e11-b411-fd799a7b835e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4OTY3OTMsIm5iZiI6MTcyODg5NjQ5MywicGF0aCI6Ii8xNzc2NDk1MDAvMzc2MTE5NTQxLWZlMTQxNTc2LTk5OTAtNGUxMS1iNDExLWZkNzk5YTdiODM1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwOTAxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTFjNWYyYzJkMDFkODJlN2NhNTVhNjYxZjQ5NjdmNjY3ODUzNDcwY2Q1Y2VmOTM2MGEwZjM4N2FkZDA1NDc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ccsyie85UyQHHlQ1rQV9pWNQ5HuH88OKAuRIF4hl_po)

改了也没有效果

**Comment by XingJi-love** [comment]
# 你执行这个命令（pnpm build）了吗？需要从新进行封装一下才可以部署

**Comment by XingJi-love** [comment]
# 请问一下你们是部署在什么上？

**Comment by ZhenHuangLab** [comment]
谢谢，我已经修复好了。我是利用github workflow部署到github pages上。

**Comment by XingJi-love** [comment]
# 好的

**Comment by zy111x** [comment]
我是在vercel上部署的，好像还是没效果

**Comment by zy111x** [comment]
> # 好的

我是在vercel上部署的，好像还是没效果

**Comment by FrecklyComb1728** [comment]
我的改成官网API也没用？
![image](https://github.com/user-attachments/assets/c3807e53-6429-468d-ba7a-c40d54b1e3de)

**Comment by XingJi-love** [comment]
> 我的改成官网API也没用？ ![image](https://private-user-images.githubusercontent.com/158593086/376628483-c3807e53-6429-468d-ba7a-c40d54b1e3de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDA1MTAsIm5iZiI6MTcyOTAwMDIxMCwicGF0aCI6Ii8xNTg1OTMwODYvMzc2NjI4NDgzLWMzODA3ZTUzLTY0MjktNDY4ZC1iYTdhLWM0MGQ1NGIxZTNkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxMzUwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWU1YzViMzdkZDkzOWY4ZTU2M2E2YmI4NzRjNzYyNjY2ZTEyYzhiMmFjZWE1YTkyZWM1OGM5YjVjZDI2ZDNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qNwSK8tw9F--lfV5rDLkM4uw7fONXFtjsSRw-mELMTY)

# 请问一下你们是部署在什么上？

**Comment by FrecklyComb1728** [comment]
你好。已收到你的邮件，我会在假期结束后尽快处理。————————————这是来自QQ邮箱的自动回复邮件。

**Comment by FrecklyComb1728** [comment]
> > 我的改成官网API也没用？![图像](https://private-user-images.githubusercontent.com/158593086/376628483-c3807e53-6429-468d-ba7a-c40d54b1e3de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDA1MTAsIm5iZiI6MTcyOTAwMDIxMCwicGF0aCI6Ii8xNTg1OTMwODYvMzc2NjI4NDgzLWMzODA3ZTUzLTY0MjktNDY4ZC1iYTdhLWM0MGQ1NGIxZTNkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxMzUwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWU1YzViMzdkZDkzOWY4ZTU2M2E2YmI4NzRjNzYyNjY2ZTEyYzhiMmFjZWE1YTkyZWM1OGM5YjVjZDI2ZDNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qNwSK8tw9F--lfV5rDLkM4uw7fONXFtjsSRw-mELMTY)
> 
> # 请问一下你们是部署在什么上？

部署在cloudflare上，本地我也试过了不行，不管是build之后用nginx还是直接用dev都不行

**Comment by XingJi-love** [comment]
我的也是部署在cloudflare上，修改后访问正常显示，https://site-status.xingji.fun/

**Comment by FrecklyComb1728** [comment]
> 我的也是部署在cloudflare上，修改后访问正常显示，https://site-status.xingji.fun/

![image](https://github.com/user-attachments/assets/893d881f-a558-42ad-89db-96693749fcac)

**Comment by FrecklyComb1728** [comment]
key是正常的

**Comment by FrecklyComb1728** [comment]
改为只读API_key就正常了？

**Comment by FrecklyComb1728** [comment]
> 我的也是部署在cloudflare上，修改后访问正常显示，https://site-status.xingji.fun/
谢谢你了已经解决了

**Comment by XingJi-love** [comment]
![屏幕截图 2024-11-20 155452](https://github.com/user-attachments/assets/102e52cf-6927-4923-96bc-13972b799cc9)
你把源码下载到本地，按照图片上的步骤： 

# 若没有 pnpm
npm install pnpm -g

# 安装依赖
pnpm install

在 .env 文件中进行配置修改，修改成你的

# 这个命令是进行本地预览
pnpm dev

# 打包
pnpm build

把 pnpm build 后得到的 dist 文件夹上传到cloudeflare 的 pages 部署一下

<img width="1280" alt="网站监控部署" src="https://github.com/user-attachments/assets/4a841b73-513b-4c79-ad30-1551b005ab4b">

**Comment by FrecklyComb1728** [comment]
虽然已经解决了，但还是谢谢你的回答
