### ISSUE TITLE
您好，想请教一下VITE_GLOBAL_APIVITE_GLOBAL_API具体的作用以及如何搭建

### ISSUE THREAD

**Issue by Asakushen** [imsyy/site-status#6]
我注意到.env中需要填入VITE_GLOBAL_API，我没做修改用的大佬填写的发现仍然可以正常部署使用，请问这个具体是起到什么作用，是否有必要进行修改，以及搭建的相关问题。谢谢您的解答！

**Comment by imsyy** [comment]
主要起到反代 UptimeRobot 的作用
自行部署可以参考这里：https://github.com/imsyy/ToolsApi
