### ISSUE TITLE
展示的监控数据，是不是应该升序更好？

### ISSUE THREAD

**Issue by kuole-o** [imsyy/site-status#8]
RT，感觉应该升序比现在降序更符合认知？一般旧的在最左边，新的在最右边吧？我昨天看了半天，还以为 UptimeRobot 挂了还是被禁用了……最后发现正常的。  
  
自己尝试改了下，一直不太行……

**Comment by kuole-o** [comment]
已自行排序解决

**Comment by q246** [comment]
> 已自行排序解决

怎么解决的 改了哪里？求大佬透露一下

**Comment by kuole-o** [comment]
> > 已自行排序解决
> 
> 怎么解决的 改了哪里？求大佬透露一下

当前我已经跟随作者最新版本 升级到 2.0 了，想在之前 1.x 版本实现排序的数据问题，[可以看个提交里的代码](https://github.com/kuole-o/site-status/tree/d41bcd310299d9ef2a18267134926603c7b219c4)
